/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.com.mtanuri.forms.model;

import com.liferay.portal.kernel.bean.AutoEscape;


/**
 * The base model interface for the Forms service. Represents a row in the &quot;MTANURI_Forms&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>br.com.mtanuri.forms.model.impl.FormsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>br.com.mtanuri.forms.model.impl.FormsImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Forms
 * @generated
 */
@ProviderType
public interface FormsModel extends BaseModel<Forms> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a forms model instance should use the {@link Forms} interface instead.
	 */

	/**
	 * Returns the primary key of this forms.
	 *
	 * @return the primary key of this forms
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this forms.
	 *
	 * @param primaryKey the primary key of this forms
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the form ID of this forms.
	 *
	 * @return the form ID of this forms
	 */
	public long getFormId();

	/**
	 * Sets the form ID of this forms.
	 *
	 * @param formId the form ID of this forms
	 */
	public void setFormId(long formId);

	/**
	 * Returns the group ID of this forms.
	 *
	 * @return the group ID of this forms
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this forms.
	 *
	 * @param groupId the group ID of this forms
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the form name of this forms.
	 *
	 * @return the form name of this forms
	 */
	@AutoEscape
	public String getFormName();

	/**
	 * Sets the form name of this forms.
	 *
	 * @param formName the form name of this forms
	 */
	public void setFormName(String formName);

	/**
	 * Returns the create date time of this forms.
	 *
	 * @return the create date time of this forms
	 */
	public long getCreateDateTime();

	/**
	 * Sets the create date time of this forms.
	 *
	 * @param createDateTime the create date time of this forms
	 */
	public void setCreateDateTime(long createDateTime);

	/**
	 * Returns the content of this forms.
	 *
	 * @return the content of this forms
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this forms.
	 *
	 * @param content the content of this forms
	 */
	public void setContent(String content);

	/**
	 * Returns the files of this forms.
	 *
	 * @return the files of this forms
	 */
	@AutoEscape
	public String getFiles();

	/**
	 * Sets the files of this forms.
	 *
	 * @param files the files of this forms
	 */
	public void setFiles(String files);

}